MinSetupCore/MinSetupCore/Controllers/Awesome/DataController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MinSetupCore.Models;

using Omu.AwesomeMvc;

namespace MinSetupCore.Controllers.Awesome
{
    public class DataController : Controller
    {
        public ActionResult GetAllMeals()
        {
            var items = Db.Meals.Select(o => new KeyContent(o.Id, o.Name));
            return Json(items);
        }
    }
}

MinSetupCore/MinSetupCore/Controllers/Awesome/Lookup/ChefLookupController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MinSetupCore.Models;
using Omu.AwesomeMvc;

namespace MinSetupCore.Controllers.Awesome.Lookup
{
    public class ChefLookupController : Controller
    {
        public ActionResult GetItem(int? v)
        {
            var o = Db.Get<Chef>(v) ?? new Chef();
            return Json(new KeyContent(o.Id, o.FirstName + " " + o.LastName));
        }

        public ActionResult Search(string search, int page)
        {
            const int PageSize = 7;
            search = (search ?? "").ToLower().Trim();

            var list = Db.Chefs.Where(f => (f.FirstName + " " + f.LastName).ToLower().Contains(search));
            return Json(new AjaxListResult
            {
                Items = list.Skip((page - 1) * PageSize).Take(PageSize).Select(o => new KeyContent(o.Id, o.FirstName + " " + o.LastName)),
                More = list.Count() > page * PageSize
            });
        }
    }
}

MinSetupCore/MinSetupCore/Controllers/Awesome/MultiLookup/MealsMultiLookupController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MinSetupCore.Models;
using Omu.AwesomeMvc;

namespace MinSetupCore.Controllers.Awesome.MultiLookup
{
    public class MealsMultiLookupController : Controller
    {
        public ActionResult GetItems(int[] v)
        {
            return Json(Db.Meals.Where(o => v != null && v.Contains(o.Id))
                            .Select(meal => new KeyContent(meal.Id, meal.Name)));
        }

        public ActionResult Search(string search, int[] selected, int page)
        {
            const int PageSize = 10;
            selected = selected ?? new int[] { };
            search = (search ?? "").ToLower().Trim();

            var items = Db.Meals.Where(o => o.Name.ToLower().Contains(search) && (!selected.Contains(o.Id)));

            return Json(new AjaxListResult
            {
                Items = items.Skip((page - 1) * PageSize).Take(PageSize).Select(o => new KeyContent(o.Id, o.Name)),
                More = items.Count() > page * PageSize
            });
        }

        public ActionResult Selected(int[] selected)
        {
            return Json(new AjaxListResult
            {
                Items = Db.Meals.Where(o => selected != null && selected.Contains(o.Id))
                    .Select(o => new KeyContent(o.Id, o.Name))
            });
        }
    }
}

MinSetupCore/MinSetupCore/Views/Shared/EditorTemplates/AjaxCheckboxList.cshtml
@{
    Layout = "_FieldLayout";
}
@Html.Awe().AjaxCheckboxList("")

MinSetupCore/MinSetupCore/Views/Shared/EditorTemplates/AjaxRadioList.cshtml
@{
    Layout = "_FieldLayout";
}
@Html.Awe().AjaxRadioList("")

MinSetupCore/MinSetupCore/Views/Shared/EditorTemplates/Boolean.cshtml
@model bool
@{
    Layout = "_FieldLayout";
    ViewData["__idpostfix"] = "-awed";
}
@Html.Awe().CheckBox("")

MinSetupCore/MinSetupCore/Views/Shared/EditorTemplates/ColorDropdown.cshtml
@{
    Layout = "_FieldLayout";
    ViewData["__idpostfix"] = "-awed";
}
@Html.Awe().AjaxRadioList("").ColorDropdown()

MinSetupCore/MinSetupCore/Views/Shared/EditorTemplates/Combobox.cshtml
@{
    Layout = "_FieldLayout";
    ViewData["__idpostfix"] = "-awed";
}
@(Html.Awe().AjaxRadioList("").Combobox())

MinSetupCore/MinSetupCore/Views/Shared/EditorTemplates/Hidden.cshtml
@model object
@Html.Hidden("", Model)

MinSetupCore/MinSetupCore/Views/Shared/EditorTemplates/Lookup.cshtml
@{
    Layout = "_FieldLayout";
}
@Html.Awe().Lookup("")

MinSetupCore/MinSetupCore/Views/Shared/EditorTemplates/LookupDropdown.cshtml
@{
    Layout = "_FieldLayout";
}
@Html.Awe().Lookup("").Mod(o => o.Dropdown())

MinSetupCore/MinSetupCore/Views/Shared/EditorTemplates/MealsOdropdown.cshtml
@{
    Layout = "_FieldLayout";
}
 @(Html.Awe().AjaxRadioList("").Odropdown().Url(Url.Action("GetAllMeals","Data")))

MinSetupCore/MinSetupCore/Views/Shared/EditorTemplates/MultiLookup.cshtml
@{
    Layout = "_FieldLayout";
}
@Html.Awe().MultiLookup("")

MinSetupCore/MinSetupCore/Views/Shared/EditorTemplates/MultiLookupDropdown.cshtml
@{
    Layout = "_FieldLayout";
}
@Html.Awe().MultiLookup("").Mod(o => o.Dropdown())

MinSetupCore/MinSetupCore/Views/Shared/EditorTemplates/Odropdown.cshtml
@{
    Layout = "_FieldLayout";
    ViewData["__idpostfix"] = "-awed";
}
@(Html.Awe().AjaxRadioList("").Odropdown())

MinSetupCore/MinSetupCore/Views/Shared/EditorTemplates/Single.cshtml
@{
    Layout = "_FieldLayout";
    ViewData["__idpostfix"] = "-awed";
}
@Html.Awe().TextBox("").Numeric().CssClass("etxt")

MinSetupCore/MinSetupCore/Views/Shared/EditorTemplates/String.cshtml
@{
    Layout = "_FieldLayout";
    ViewData["__idpostfix"] = "-awed";
}
@Html.Awe().TextBox("").CssClass("etxt")